# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171203_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=40),
        ),
    ]
