# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=40, null=True),
        ),
    ]
